version: '3.3'

services:

    apache:
        image: httpd:2.4
        container_name: apache
        stdin_open: true
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs/
        restart: unless-stopped 

        
